FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["./DeliveryService.Backend/DeliveryService.Backend.csproj", "DeliveryService.Backend/"]
RUN dotnet restore "DeliveryService.Backend/DeliveryService.Backend.csproj"
COPY . .

WORKDIR "/src/DeliveryService.Backend"
RUN dotnet build "DeliveryService.Backend.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "DeliveryService.Backend.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "DeliveryService.Backend.dll"]